apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2024-05-01T17:51:14Z"
  labels:
    kubernetes.io/metadata.name: guestbook
  name: guestbook
  resourceVersion: "9377"
  uid: 7dcffd88-09e2-4ccc-8a59-cbda4d0e6990
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: guestbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
